version: '3.8'

services:
  # Build and push backend image
  backend-build:
    build:
      context: ./carfinder
      Dockerfile: Dockerfile
    image: 192.168.1.72:/carfinder-api::v1.0.0
    container_name: carfinder_backend_build
    profiles:
      - build

  # Build and push frontend image  
  frontend-build:
    build:
      context: ./carfinder-ui
      Dockerfile: Dockerfile
    image: 192.168.1.72:carfinder-ui::v1.0.0
    container_name: carfinder_frontend_build
    profiles:
      - build
