version: '3.8'

services:
  # Build and push backend image
  backend-build:
    build:
      context: ./carfinder
      dockerfile: dockerfile
    image: 192.168.1.72:/carfinder-api:latest
    container_name: carfinder_backend_build
    profiles:
      - build

  # Build and push frontend image  
  frontend-build:
    build:
      context: ./carfinder-ui
      dockerfile: dockerfile
    image: 192.168.1.72:carfinder-ui:latest
    container_name: carfinder_frontend_build
    profiles:
      - build
