version: '3.8'

services:
  frontend:
    build:
      context: ./carfinder-ui
      dockerfile: dockerfile
    image:  10.83.64.110:8085/carfinder-ui:latest
    container_name: carfinder_frontend
    # Remove ports and depends_on since we're just building/pushing
    networks:
      - carfinder_network

  backend:
    build:
      context: ./carfinder
      dockerfile: dockerfile
    image:  10.83.64.110:8085/carfinder-api:latest
    container_name: carfinder_backend
    # Remove ports and environment since we're just building/pushing
    networks:
      - carfinder_network

networks:
  carfinder_network:
    driver: bridge